from __future__ import annotations

import logging
import os
import time
import uuid
from dataclasses import dataclass
from pathlib import Path

from fastapi import UploadFile

from src.core.env import get_int_env
from src.core.exceptions import InvalidUploadError, StorageError, UploadTooLargeError
from src.core.sanitize import clean_text

logger = logging.getLogger(__name__)

_DEFAULT_MAX_MB = 10
_DEFAULT_UPLOAD_DIR = Path("data/uploads")
_ALLOWED_MIME = "application/pdf"
_PDF_MAGIC = b"%PDF-"
_CHUNK_SIZE = 64 * 1024
_DISPLAY_NAME_MAX = 100
_FALLBACK_NAME = "document.pdf"
_STALE_UPLOAD_SECONDS = 3_600
_O_BINARY = getattr(os, "O_BINARY", 0)  # Windows: no newline translation


@dataclass(frozen=True)
class StoredUpload:
    """An upload saved on disk under a server-generated name.

    Attributes:
        path: Where the PDF is stored (name generated by the server, never the client's).
        display_name: The client's file name, sanitised: for display only, never a path.
        size: Size in bytes.
    """

    path: Path
    display_name: str
    size: int


def max_upload_bytes() -> int:
    return get_int_env("MAX_UPLOAD_SIZE_MB", _DEFAULT_MAX_MB) * 1024 * 1024


def upload_dir() -> Path:
    # Read at call time so tests / deployments can override it. Never a served directory.
    return Path(os.getenv("UPLOAD_DIR", str(_DEFAULT_UPLOAD_DIR)))


def display_name(filename: str | None) -> str:
    """Turn a client-supplied file name into a safe label (basename, no control chars)."""
    if not filename:
        return _FALLBACK_NAME
    basename = filename.replace("\\", "/").rsplit("/", 1)[-1]
    return clean_text(basename, _DISPLAY_NAME_MAX) or _FALLBACK_NAME


async def save_upload(file: UploadFile) -> StoredUpload:
    """Validate and store an uploaded PDF under a server-generated name.

    Checks: declared MIME type, first bytes (`%PDF-`), non-empty, size counted while
    writing (the `Content-Length` header is never trusted). On any failure the partial
    file is removed.

    Raises:
        InvalidUploadError: Wrong MIME type, not a PDF, or empty file.
        UploadTooLargeError: More than MAX_UPLOAD_SIZE_MB.
        StorageError: The file cannot be written.
    """
    mime = (file.content_type or "").split(";")[0].strip().lower()
    if mime != _ALLOWED_MIME:
        raise InvalidUploadError("Unsupported content type")

    limit = max_upload_bytes()
    directory = upload_dir()
    target = directory / f"{uuid.uuid4().hex}.pdf"
    size = 0

    try:
        directory.mkdir(parents=True, exist_ok=True, mode=0o700)
        # O_EXCL: never overwrite an existing file; 0o600: owner only (POSIX).
        descriptor = os.open(target, os.O_WRONLY | os.O_CREAT | os.O_EXCL | _O_BINARY, 0o600)
        with os.fdopen(descriptor, "wb") as out:
            first_chunk = True
            while chunk := await file.read(_CHUNK_SIZE):
                if first_chunk:
                    if not chunk.startswith(_PDF_MAGIC):
                        raise InvalidUploadError("File does not start with %PDF-")
                    first_chunk = False
                size += len(chunk)
                if size > limit:
                    raise UploadTooLargeError(f"Upload larger than {limit} bytes")
                out.write(chunk)
        if size == 0:
            raise InvalidUploadError("Empty file")
    except OSError as exc:
        target.unlink(missing_ok=True)
        raise StorageError(f"Cannot store upload: {type(exc).__name__}") from exc
    except BaseException:
        target.unlink(missing_ok=True)
        raise

    return StoredUpload(path=target, display_name=display_name(file.filename), size=size)


def delete_upload(path: Path) -> None:
    """Delete a stored upload (personal data: it must not outlive its processing).

    Only files directly inside UPLOAD_DIR are deleted, as a safety net against a wrong
    path ever reaching this function. Failing to delete is logged, not raised, so that it
    can be called from a `finally` block without hiding the original error.
    """
    directory = upload_dir().resolve()
    if path.resolve().parent != directory:
        logger.error("Refusing to delete a file outside the upload directory: %r", path.name)
        return
    try:
        path.unlink(missing_ok=True)
    except OSError as exc:
        logger.warning("Cannot delete upload %r: %s", path.name, exc)


def purge_stale_uploads(max_age_seconds: int = _STALE_UPLOAD_SECONDS) -> int:
    """Delete uploads left behind by a crash (GDPR: no orphan personal data). Run at startup.

    Returns:
        Number of files deleted.
    """
    directory = upload_dir()
    if not directory.is_dir():
        return 0
    deleted = 0
    for entry in directory.iterdir():
        try:
            if entry.is_file() and time.time() - entry.stat().st_mtime > max_age_seconds:
                entry.unlink(missing_ok=True)
                deleted += 1
        except OSError as exc:
            logger.warning("Cannot purge %r: %s", entry.name, exc)
    return deleted
